archives:
    - files:
          # Ensure only built binary is archived
          - "none*"
      format: zip
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
before:
    hooks:
        - go mod tidy
builds:
    - binary: "{{ .ProjectName }}_v{{ .Version }}"
      env:
          - CGO_ENABLED=0
      flags:
          - -trimpath
      mod_timestamp: "{{ .CommitTimestamp }}"
      goos:
          - freebsd
          - windows
          - linux
          - darwin
      goarch:
          - amd64
          - "386"
          - arm
          - arm64
      ignore:
          - goos: darwin
            goarch: "386"
      ldflags:
          - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
checksum:
    algorithm: sha256
    extra_files:
        - glob: "terraform-registry-manifest.json"
          name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
    name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
release:
    extra_files:
        - glob: "terraform-registry-manifest.json"
          name_template: "{{ .ProjectName }}_{{ .Version }}_manifest.json"
    ids:
        - none
signs:
    - args:
          [
              "sign",
              "--dearmor",
              "--file",
              "${artifact}",
              "--out",
              "${signature}",
          ]
      artifacts: checksum
      cmd: signore
      signature: ${artifact}.sig
    - args:
          [
              "sign",
              "--dearmor",
              "--file",
              "${artifact}",
              "--out",
              "${signature}",
          ]
      artifacts: checksum
      cmd: signore
      id: key-id
      signature: ${artifact}.72D7468F.sig
