package docs

const (
	ApplicationResource     = "Your Sendbird application provides core functionalities that ensure optimal performance of your chat service."
	ApplicationResourceId   = "Application id generated by Sendbird."
	ApplicationResourceName = "Specifies the unique name of the application. This parameter is case-insensitive. " +
		"While this value could change without replacing the application, " +
		"Sendbird isn't exposing an API to modify the name. If a name change is required, it is possible to " +
		"change the value on the console and in the configuration. The next terraform apply will appropriately " +
		"detect the change and won't replace the application"
	ApplicationResourceApiToken = "Master API Token. To be authenticated by Sendbird server, your request should " +
		"include one of the listed API tokens. For further information, see the Authentication page in the " +
		"[documentation](https://sendbird.com/docs/chat/platform-api/v3/prepare-to-use-api#2-authentication)"
	ApplicationResourceCreatedAt = "Application creation timestamp. Format: yyyy-mm-ddThh:mm:ssZ"
	ApplicationResourceRegionKey = "Specifies the code of the region. Acceptable values are listed on the [Sendbird Dashboard]" +
		"(https://dashboard.sendbird.com/auth/signin) under Organization settings > General > API Key > Regions. This value can't be changed " +
		"after the application is created. Any change would result in replacing the application."
	ApplicationResourceRegionName = "User friendly name for the region."
)

const (
	ApplicationDataSource           = "Use this data source to get the value of the master API Token and or get Region information"
	ApplicationDataSourceId         = ApplicationResourceId
	ApplicationDataSourceName       = "Application Name"
	ApplicationDataSourceApiToken   = ApplicationResourceApiToken
	ApplicationDataSourceCreatedAt  = ApplicationResourceCreatedAt
	ApplicationDataSourceRegionKey  = "Key for the region where the application was created."
	ApplicationDataSourceRegionName = ApplicationResourceRegionName
)
